### ISSUE TITLE
[1.18.2] Invalid datapack

### ISSUE THREAD

**Issue by Nekkok** [AlexJ314/Whitelist-Minecraft-Biomes#2]
Hi! I found your awesome tool and wanted to try it to make a custom world but first of all I must warn I have no experience with worldgen datapacking.

For now I'm just testing it and I've come to this _world_preset/normal.json_ which I put inside kubejs folder which lets loading datapacks without making one.

Im sharing you my log and the normal.json hoping you can tell me what's wrong with these. Thanks!
[normal.json](https://gist.github.com/Nekkok/cc72b58e78df64cafa116f26bc166104)
[latest.log](https://github.com/AlexJ314/Whitelist-Minecraft-Biomes/files/11253428/latest.log)

**Comment by AlexJ314** [comment]
Hello, thanks for reaching out!
I'm looking at the files you've linked now and will let you know what I find.
In the meantime, though, you may want to remove your `latest.log` file from your comment at it could contain sensitive information.

**Comment by AlexJ314** [comment]
Ok, I don't know much about KubeJS, but appears as though it'll convert JavaScript to Java. This won't be terribly useful for this datapack as it is written in Json and meant to override default Minecraft Json files. Try loading your world without this datapack and then try loading the world with this datapack in its complete form according to the ReadMe.

It is also entirely possible that because you are running 1.18.2 and the `normal.json` expects 1.19.x, that there are some new generation settings. Find the 1.18.2 settings from https://github.com/slicedlime/examples/commits/master and see if that fixes things.
